---

- name: Make DSpace install destination folders
  file: 
    path: "{{ item }}"
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0755
  loop:
    - "{{ dspace_install_dir }}" 
    - "{{ dspace_install_dir }}/dspace"        
    - "{{ dspace_install_dir }}/dspace-src"
    - "{{ dspace_install_dir }}/etc"     
    - "{{ dspace_install_dir }}/bin"     

- name: Set SELinux context for dspace files
  command: >
          semanage fcontext -a -t tomcat_var_lib_t  "{{ dspace_install_dir }}(/.*)?"

- name: Install build config
  template:
    src: conf.sh.j2
    dest: "{{ dspace_install_dir }}/etc/conf.sh"

- name: Install build scripts
  template:
    mode: 0755
    src: "{{item.src}}" 
    dest: "{{ dspace_install_dir }}/bin/{{item.dest}}"
  loop:
    - src: build.sh.j2
      dest: build.sh
    - src: clean.sh.j2
      dest: clean.sh
    - src: fix_perms.sh.j2
      dest: fix_perms.sh
    - src: git_pull.sh.j2
      dest: git_pull.sh
