---
- name: Install psycopg2 python module
  pip:
    name: psycopg2-binary

- name: Create postgresql DB user
  become: True
  become_user: postgres
  postgresql_user:
    name: "{{ dspace_db_user }}"
    password: "{{ dspace_db_pass }}"
    role_attr_flags: NOSUPERUSER
    encrypted: yes

- name: Create postgresql database
  become: True
  become_user: postgres
  postgresql_db:
    name: "{{dspace_db_name }}"
    owner: "{{ dspace_db_user }}"
    encoding: UNICODE

- name: Enable pgcrypto DB Extension
  become: True
  become_user: postgres
  postgresql_ext:
    name: pgcrypto
    db: "{{ dspace_db_name }}"
