---
- name: Build  DSpace
  command: "{{ dspace_install_dir }}/bin/build.sh"
  when: true
  register: dspace_build_result

- block:
    - name: Install DSpace
      command: "{{ dspace_install_dir }}/bin/install.sh"
    - name: Fix  DSpace permissions
      command: "{{ dspace_install_dir }}/bin/fix_perms.sh"
  when: dspace_build_result is succeeded
