---
- name: Install dspace dependencies
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - java-1.8.0-openjdk
    - maven
    - ant
    - tomcat
    - tomcat-webapps
    - tomcat-admin-webapps

- name: Install psycopg2 python module
  pip:
    name: psycopg2

- name: Create temp dSpace6 unpack directory
  file:
    path: /tmp/dspace6
    state: directory
    owner: tomcat
    mode: 0755

- name: Create dSpace6 install directory
  file:
    path: /srv/oulib/dspace6
    state: directory
    owner: tomcat
    mode: 0755

- name: Download dSpace6 Binary
  get_url:
    url: https://github.com/DSpace/DSpace/releases/download/dspace-6.1/dspace-6.1-release.tar.gz
    dest: /tmp/dspace6-current.tar.gz

- name: Unarchive dSpace6 Binary
  unarchive:
    src: /tmp/dspace6-current.tar.gz
    dest: /tmp/dspace6/
    owner: tomcat
    group: tomcat 

- name: Create postgresql DB user
  become: True
  become_user: postgres
  postgresql_user:
    name: dspace
    password: dspace
    role_attr_flags: NOSUPERUSER

- name: Create postgresql database
  become: True
  become_user: postgres
  postgresql_db:
    name: dspace
    owner: dspace
    encoding: UNICODE

- name: Enable pgcrypto DB Extension
  become: True
  become_user: postgres
  postgresql_ext:
    name: pgcrypto
    db: dspace

#- name: Create folder for oulib/dspace scripts
#  file:
#    path: /opt/oulib/dspace/bin
#    state: directory
#
#- name: Create folder for oulib/dspace config
#  file:
#    path: /opt/oulib/dspace/etc
#    state: directory
#
- name: Create script configuration file
  template:
    src: conf.j2
    dest: /tmp/dspace6/dspace-6.1-release/dspace/config/local.cfg
    backup: yes

- name: Create xmlui configuration file
  template:
    src: xmlui.xconf.j2
    dest: /tmp/dspace6/dspace-6.1-release/dspace/config/xmlui.xconf
    backup: yes

- name: Build the dSpace6 installation package
  become: True
  become_user: tomcat
  shell: |
    mvn package -Dmirage2.on=true
  args:
    chdir: /tmp/dspace6/dspace-6.1-release/

- name: Install dSpace6
  become: True
  become_user: tomcat
  shell: |
    ant fresh_install
  args:
    chdir: /tmp/dspace6/dspace-6.1-release/dspace/target/dspace-installer


- name: Create xmlui.xml file
  template:
    src: xmlui.xml.j2
    dest: /etc/tomcat/Catalina/localhost/xmlui.xml
    backup: yes

- name: Create solr.xml file
  template:
    src: solr.xml.j2
    dest: /etc/tomcat/Catalina/localhost/solr.xml
    backup: yes

- name: Create oai.xml file
  template:
    src: oai.xml.j2
    dest: /etc/tomcat/Catalina/localhost/oai.xml
    backup: yes

- name: Create rdf.xml file
  template:
    src: rdf.xml.j2
    dest: /etc/tomcat/Catalina/localhost/rdf.xml
    backup: yes

- name: Create sword.xml file
  template:
    src: sword.xml.j2
    dest: /etc/tomcat/Catalina/localhost/sword.xml
    backup: yes

- name: Create rest.xml file
  template:
    src: rest.xml.j2
    dest: /etc/tomcat/Catalina/localhost/rest.xml
    backup: yes








#
#- name: Install scripts
#  copy:
#    src: "{{ item }}"
#    dest: /opt/oulib/dspace/bin/
#  with_items:
#    - ds_build.sh
#    - ds_clean.sh
#    - ds_exportdb.sh
#    - ds_reconfigure.sh
#
#- name: Ensure /etc/profile.d/oulib-dspace.sh exists
#  file:
#    path: /etc/profile.d/oulib-dspace.sh
#    state: touch
#    mode: 0644
#    owner: root
#    group: root
#
#- name: Add oulib/dspace scripts to path
#  lineinfile:
#    dest: /etc/profile.d/oulib-dspace.sh
#    line: 'export PATH=/opt/oulib/dspace/bin:$PATH'
#    
#- name: Add oulib/dspace scripts to sudo secure_path
#  lineinfile:
#    dest: /etc/sudoers
#    state: present
#    regexp: '^Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin$'
#    line: 'Defaults    secure_path = /opt/oulib/dspace/bin:/sbin:/bin:/usr/sbin:/usr/bin'
#    validate: 'visudo -cf %s'
#
#    
#- name: Save public key to file
#  copy:
#    content: "{{ hostvars.localhost.deploy_public_key }}"
#    dest: "/home/vagrant/.ssh/libdev_rsa.pub"
#    mode: 0600
#    owner: vagrant
#    group: vagrant
#
#- name: Save private key to file
#  copy:
#    content: "{{ hostvars.localhost.deploy_private_key }}"
#    dest: "/home/vagrant/.ssh/libdev_rsa"
#    mode: 0600
#    owner: vagrant
#    group: vagrant
#
#- name: Create .m2 folder for maven repository
#  file:
#    path: "/home/vagrant/.m2"
#    state: directory
#    mode: 0770
#    owner: vagrant
#    group: vagrant
# 
#- name: Create maven settings file with @mire credentials
#  template:
#    src: m2_settings.xml.j2
#    dest: "/home/vagrant/.m2/settings.xml"
#    mode: 0644
#    owner: vagrant
#    group: vagrant



