---
# Install Tomcat and configure for DSpace

- name: Install Tomcat RPMs
  yum:
    name:
      - tomcat
      - tomcat-webapps
      - tomcat-admin-webapps

- name: Update tomcat server config
  template:
    src:  "tomcat-server.xml.j2"
    dest: "/etc/tomcat/server.xml"

- name: Update tomcat logging config
  template:
    src:  "tomcat-logging.properties.j2"
    dest: "/etc/tomcat/logging.properties"

- name: Update tomcat logrotate config
  template:
    src:  "logrotate_tomcat.j2"
    dest: "/etc/logrotate.d/tomcat"

- name: Configure Tomcat for DSpace web apps.
  template:
    src: "{{ item.src }}"
    dest: "/etc/tomcat/Catalina/localhost/{{ item.dest }}"
  loop:
    - src: ROOT.xml.j2
      dest: ROOT.xml
    - src: solr.xml.j2
      dest: solr.xml
    - src: oai.xml.j2
      dest: oai.xml
    - src: rdf.xml.j2
      dest: rdf.xml
    - src: sword.xml.j2
      dest: sword.xml
    - src: rest.xml.j2
      dest: rest.xml

- name: Configure tomcat user .bowerrc for building Mirage2
  copy:
    owner: tomcat
    group: tomcat
    dest: "/usr/share/tomcat/.bowerrc"
    content: |
      {
        "registry": "https://registry.bower.io"
      }

- name: Update tomcat config
  template:
    src: "tomcat.conf.j2"
    dest: "/etc/tomcat/tomcat.conf"


# These can end up with a value that won't work for the tomcat service because
# we build DSpace as tomcat.
- name: Set SELinux tomcat hsperfdata
  command: >
          semanage fcontext -a -t tomcat_tmp_t  "/tmp/hsperfdata_tomcat(/.*)?"

- name: Set SELinux booleans
  seboolean:
    name: tomcat_can_network_connect_db
    state: yes

- name: Install JMX user file
  template:
    src: jmxremote.access.j2
    dest: "{{ dspace_install_dir }}/etc/jmxremote.access"
  when: dspace_jmx_user is defined

- name: Install JMX password file
  template:
    src: jmxremote.password.j2
    dest: "{{ dspace_install_dir }}/etc/jmxremote.password"
    mode: 0600
  when: dspace_jmx_user is defined

- name: Install tomcat crontab for dspace
  template:
    dest: /var/spool/cron/tomcat
    src: tomcat-cron.j2
    mode: 0600
    owner: tomcat
    group: tomcat
